language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t zhafa467/docker-react -f Dockerfile.dev . 

scripts:
  - docker run -e CI=true zhafa467/docker-react npm run test

deploy:
  provider: elasticbeanstalk 
  region: "ap-southeast-2"
  app: "Docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-476290624158"
  bucket_path: "Docker-react"
  on:
    branch:
      - master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
