language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t zhafa467/docker-react -f Dockerfile.dev . 

scripts:
  - docker run -e CI=true zhafa467/docker-react npm run test